# Generated by Django 3.0.2 on 2020-02-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_defaultanswer_question_registrationanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
