# Generated by Django 3.0.2 on 2020-02-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20200209_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrationanswer',
            name='question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.Question'),
            preserve_default=False,
        ),
    ]
