# Generated by Django 3.0.2 on 2020-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20200212_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='accepted',
            field=models.CharField(choices=[('AC', 'Zaakceptowane'), ('RE', 'Odrzucone'), ('WA', 'Oczekujące')], default='WA', max_length=2),
        ),
    ]
