# Generated by Django 3.0.3 on 2020-02-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20200215_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='accepted',
            field=models.CharField(choices=[('AC', 'Zaakceptowane'), ('RE', 'Odrzucone'), ('WA', 'Oczekujące')], default='WA', max_length=2),
        ),
    ]
