# Generated by Django 3.0.3 on 2020-02-15 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20200215_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
