# Generated by Django 3.0.2 on 2020-02-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20200215_2023'),
        ('workshop', '0009_workshop_end_date'),
    ]

    operations = [
    ]
