# Generated by Django 3.0.2 on 2020-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_merge_20200216_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultAnswer',
            new_name='AnswerOption',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
