# Generated by Django 3.0.2 on 2020-02-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_auto_20200217_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='workshop_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='workshop.WorkshopRegistration'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='accepted',
            field=models.CharField(choices=[('AC', 'Zaakceptowane'), ('RE', 'Odrzucone'), ('WA', 'Oczekujące'), ('WL', 'Lista rezerwowa')], default='WA', max_length=2),
        ),
    ]
